repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v3.4.0
        hooks:
            -   id: end-of-file-fixer
                types: [ python ]
    -   repo: https://github.com/pycqa/isort
        rev: 5.8.0
        hooks:
            -   id: isort
                name: isort (python)
    -   repo: https://gitlab.com/pycqa/flake8
        rev: 3.8.4
        hooks:
            -   id: flake8
                types: [ python ]
